name: cypress

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-20.04
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: listmonk
          POSTGRES_USER: listmonk
          POSTGRES_DB: listmonk
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Prepare Dependencies
        run: make deps

      - name: Build Listmonk Binary
        run: |
          export PATH=$PATH:/home/runner/go/bin/
          make dist

      - name: Run Listmonk Server
        run: |
           ./listmonk --install --yes --config config-ci.toml
           ./listmonk --config config-ci.toml &
  
      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend 
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:9000'
          config-file: cypress.json
